### ISSUE TITLE
1.0.0 Checklist

### ISSUE THREAD

**Issue by mOctave** [mOctave/blended-ships#1]
- [x] Start using GitHub Actions
  - [x] Implement warp's CI tests
  - [x] Get Codespell configured and running
  - [x] Set up Dependabot to keep actions up to date
- [x] Add new ships
  - [x] a one-of-a-kind dreadnought kitbash (Barquentine)
    - [x] remove diffuse and glossy ray visibility
  - [x] a pleasure craft based on a disused Lance (Partisan)
  - [x] A Wasp-Barb splice (Hornet)
  - [x] A freight version of the Sunder
- [x] Do bugfixes
- [x] Make sure the copyright file contains all proper attributions
- [x] Get a proper changelog implemented
- [x] Add Enforcer to the Greenrock shipyard
