### ISSUE TITLE
1.2.0 Checklist

### ISSUE THREAD

**Issue by mOctave** [mOctave/blended-ships#5]
- [ ] Add a Tier 3 Pug light warship
- [ ] Add new alien splices:
  - [x] Successors
  - [x] Gegno
  - [ ] Bunrodea
  - [ ] Wanderers
- [x] Make Omnis support better (new system with content from all my plugins?)

**Comment by TheGiraffe3** [comment]
I could help with Omnis support.

**Comment by mOctave** [comment]
I think I can figure it out. But I'll be sure to ask you if I find out I can't.

**Comment by mOctave** [comment]
The Pug, Bunrodea, and Wanderers splices are going to have to wait for 1.3, because 1.2 has been released.
